services:

  api:
    build:
      context: .
      target: dev
      args:
        DEV: true
    container_name: project-contributors-api-dev
    ports:
        - "3000:3000"
    volumes:
      - ./project-contributors-api:/app/project-contributors-api
    env_file:
      - .env.dev