# Generated by Django 5.1.6 on 2025-02-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
