# Generated by Django 5.1.6 on 2025-02-10 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributor", "0002_alter_contributor_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributorskillset",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skillset",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
